# Generated by Django 5.0.6 on 2025-11-02 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_citizen', models.BigIntegerField(db_index=True)),
                ('url_document', models.URLField(max_length=500)),
                ('document_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Authenticated Successfully'), ('FAILED', 'Authentication Failed'), ('ERROR', 'Error During Processing')], default='PENDING', max_length=20)),
                ('auth_success', models.BooleanField(default=False)),
                ('external_api_status_code', models.IntegerField(blank=True, null=True)),
                ('external_api_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('event_published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Document Authentication',
                'verbose_name_plural': 'Document Authentications',
                'db_table': 'document_authentications',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['id_citizen', '-received_at'], name='document_au_id_citi_8394cc_idx'), models.Index(fields=['status', '-received_at'], name='document_au_status_998b63_idx')],
            },
        ),
    ]
