# Generated by Django 5.0.6 on 2025-11-07 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAuthenticationTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('document_id', models.CharField(db_index=True, max_length=255)),
                ('id_citizen', models.BigIntegerField(db_index=True)),
                ('document_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent to Centralizer'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('authenticated', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('external_api_status_code', models.IntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('event_published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Authentication Trace',
                'verbose_name_plural': 'Authentication Traces',
                'db_table': 'document_authentication_traces',
                'ordering': ['-received_at'],
            },
        ),
        migrations.DeleteModel(
            name='DocumentAuthentication',
        ),
        migrations.AddIndex(
            model_name='documentauthenticationtrace',
            index=models.Index(fields=['id_citizen', '-received_at'], name='document_au_id_citi_d5accd_idx'),
        ),
    ]
