# Generated by Django 5.0.6 on 2025-11-07 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenRegistrationTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(db_index=True, unique=True)),
                ('id_citizen', models.BigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent to Centralizer'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='PENDING', max_length=20)),
                ('external_api_status_code', models.IntegerField(blank=True, null=True)),
                ('external_api_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registration Trace',
                'verbose_name_plural': 'Registration Traces',
                'db_table': 'citizen_registration_traces',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['id_citizen', '-received_at'], name='citizen_reg_id_citi_6f2102_idx')],
            },
        ),
    ]
