# Generated by Django 5.0.6 on 2025-11-07 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenValidationTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.CharField(db_index=True, max_length=50)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('EXISTS', 'Exists in Centralizer'), ('NOT_EXISTS', 'Does Not Exist'), ('ERROR', 'Error')], max_length=20)),
                ('external_api_status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Validation Trace',
                'verbose_name_plural': 'Validation Traces',
                'db_table': 'citizen_validation_traces',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['citizen_id', '-requested_at'], name='citizen_val_citizen_8a7bfa_idx')],
            },
        ),
    ]
